package by.bsuir.kaziukovich.task15.runner;

import by.bsuir.kaziukovich.common.ConsoleScanner;
import by.bsuir.kaziukovich.task12.book.Book;
import by.bsuir.kaziukovich.task15.bookcomparators.*;
import java.util.ArrayList;
import java.util.Comparator;

/**
 * Class to show implementation of task 15
 */
public class Task15Runner {
    /**
     * Creates book by user input
     * @return Book generated by user input
     */
    private static Book getBookFromInputBook() {
        String author, title, isbn;
        int price;

        System.out.print("Enter book title: ");
        title = ConsoleScanner.getString();
        System.out.print("Enter book author: ");
        author = ConsoleScanner.getString();
        System.out.print("Enter book price: ");
        price = ConsoleScanner.getNonNegativeInt();
        System.out.print("Enter book ISBN: ");
        isbn = ConsoleScanner.getString();

        return new Book(title, author, price, isbn);
    }

    /**
     * Creates list of all comparators to show
     * @return List of all comparators to show
     */
    private static ArrayList<Comparator<Book>> getComparators() {
        ArrayList<Comparator<Book>> comparators = new ArrayList<>();

        comparators.add(new BookTitleComparator());
        comparators.add(new BookTitleAuthorComparator());
        comparators.add(new BookAuthorTitleComparator());
        comparators.add(new BookAuthorTitlePriceComparator());
        return comparators;
    }

    /**
     * Entry point for program
     * @param args CLI arguments, not in use
     */
    public static void main(String[] args) {
        ArrayList<Book> bookList = new ArrayList<>();
        int booksCount;
        ArrayList<Comparator<Book>> comparators = getComparators();

        System.out.print("Enter number of books to sort: ");
        booksCount = ConsoleScanner.getNonNegativeInt();

        for (int i = 0; i < booksCount; i++) {
            try {
                System.out.println("Enter book " + (i + 1) + " out of " + booksCount + " info");
                bookList.add(getBookFromInputBook());
            } catch (IllegalArgumentException e) {
                System.out.println("Input error: " + e.getMessage());
                i--;
            }
        }

        for (Comparator<Book> comparator : comparators) {
            bookList.sort(comparator);
            System.out.println("Books sorted by " + comparator.toString().replaceAll("\\w+\\.", "")
                    + ": ");
            System.out.println('\t' + bookList.toString());
        }
    }
}
