package by.bsuir.kaziukovich.task12.runner;

import by.bsuir.kaziukovich.common.ConsoleScanner;
import by.bsuir.kaziukovich.task12.book.Book;

/**
 * Runner to show task 12 implementation
 */
public class Task12Runner {
    /**
     * Creates book by user input
     * @return Book generated by user input
     */
    private static Book inputBook() {
        String author;
        String title;
        int price;
        String isbn;

        System.out.print("Enter book title: ");
        title = ConsoleScanner.getString();
        System.out.print("Enter book author: ");
        author = ConsoleScanner.getString();
        System.out.print("Enter book price: ");
        price = ConsoleScanner.getNonNegativeInt();
        System.out.print("Enter book ISBN: ");
        isbn = ConsoleScanner.getString();

        return new Book(title, author, price, isbn);
    }

    /**
     * Entry point for program
     * @param args CLI arguments, not in use
     */
    public static void main(String[] args) {
        Book book1;
        Book book2;

        try {
            System.out.println("Fill book 1 info");
            book1 = inputBook();
            System.out.println("Fill book 2 info");
            book2 = inputBook();
        } catch (IllegalArgumentException e) {
            System.out.println("Input error: " + e.getMessage());
            return;
        }

        System.out.print("Enter book edition: ");
        Book.setEdition(ConsoleScanner.getNonNegativeInt());

        System.out.println("Are books equal? " + book1.equals(book2));

        System.out.println("Books hash codes:");
        System.out.println("\tBook 1: " + book1.hashCode());
        System.out.println("\tBook 2: " + book2.hashCode());

        System.out.println("Books string representation:");
        System.out.println("\tBook 1: " + book1.toString());
        System.out.println("\tBook 2: " + book2.toString());

        System.out.println("Book 1 to book 2 compare result: " + book1.compareTo(book2));
    }

    /**
     * Constructor to avoid object creation
     */
    private Task12Runner() {}
}
